package com.example.whatsinfridge.data.model

import android.os.Parcelable
import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.android.parcel.Parcelize

@Parcelize
@Entity(tableName = "products_table")
data class ProductEntity(

    // TODO - implement all the fields necessary for a product entry

    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val name: String,
    val expirationDate: String, // TODO - change to proper type
    val category: String
    //val amount: Int,
    //@Embedded
    //val metadata: ProductMetadata TODO - use separated classes like this
): Parcelable {
    // TODO - move PrimaryKey down here
    /*
        PrimaryKey is moved to body.
        It's autogenerated and we don't need to specify it while creating a new ProductEntity.
     */
    /*
    @PrimaryKey(autoGenerate = true)
    var id: Int = 0
     */
}

data class ProductMetadata(
    val producent: String,
    val country: String
)